### ISSUE TITLE
Serverwide compatibility issue (Crash) (1.16.5)

### ISSUE THREAD

**Issue by TH34N0M4LY** [PaintNinja/Presence-Footsteps-Forge#28]
Every time i try to launch my server (using ATERNOS atm) It crashes due toa fatal error if this ever gets fixed i will be forever greatful:

<html>
<body>

at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[forge.jar:36.2] {}
33 | -- MOD presencefootsteps --
34 | Details:
35 | Mod File: presencefootsteps-r29-1.16.4.jar
36 | Failure message: Presence Footsteps (presencefootsteps) has failed to load correctly
37 | java.lang.RuntimeException: Attempted to load class net/minecraft/client/entity/player/ClientPlayerEntity for invalid dist DEDICATED_SERVER
38 | Mod Version: r29-1.16.4
39 | Mod Issue URL: NOT PROVIDED
40 | Exception message: java.lang.RuntimeException: Attempted to load class net/minecraft/client/entity/player/ClientPlayerEntity for invalid dist DEDICATED_SERVER
41 | Stacktrace:
42 | at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[forge.jar:36.2] {}
43 | at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.1.3.jar:?] {}
44 | at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.1.3.jar:?] {}
45 | at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.1.3.jar:?] {}
46 | at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.1.3.jar:?] {re:classloading}
47 | at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.1.3.jar:?] {re:classloading}
48 | at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_382] {}
49 | at java.lang.Class.forName0(Native Method) ~[?:1.8.0_382] {}
50 | at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_382] {}
51 | at net.minecraftforge.fml.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:61) ~[forge:?] {re:classloading}
52 | at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_382] {re:computing_frames}
53 | at net.minecraftforge.fml.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:48) ~[forge:?] {re:classloading}
54 | at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:77) ~[forge:36.2] {re:classloading}
55 | at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:106) ~[forge:?] {re:classloading}
56 | at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) ~[?:1.8.0_382] {}
57 | at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632) ~[?:1.8.0_382] {}
58 | at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_382] {}
59 | at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_382] {}
60 | at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_382] {}
61 | at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) ~[?:1.8.0_382] {}
62 |  
63

<br class="Apple-interchange-newline">
</body>
</html>at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[forge.jar:36.2] {}
-- MOD presencefootsteps --
Details:
	Mod File: presencefootsteps-r29-1.16.4.jar
	Failure message: Presence Footsteps (presencefootsteps) has failed to load correctly
		java.lang.RuntimeException: Attempted to load class net/minecraft/client/entity/player/ClientPlayerEntity for invalid dist DEDICATED_SERVER
	Mod Version: r29-1.16.4
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.RuntimeException: Attempted to load class net/minecraft/client/entity/player/ClientPlayerEntity for invalid dist DEDICATED_SERVER
Stacktrace:
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[forge.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.1.3.jar:?] {re:classloading}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.1.3.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_382] {}
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_382] {}
	at java.lang.Class.forName(Class.java:[34](https://aternos.org/files/crash-reports/crash-2023-10-26_14.54.04-fml.txt#L34)8) ~[?:1.8.0_382] {}
	at net.minecraftforge.fml.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:61) ~[forge:?] {re:classloading}
	at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_382] {re:computing_frames}
	at net.minecraftforge.fml.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:48) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:77) ~[forge:[36](https://aternos.org/files/crash-reports/crash-2023-10-26_14.54.04-fml.txt#L36).2] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:106) ~[forge:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) ~[?:1.8.0_[38](https://aternos.org/files/crash-reports/crash-2023-10-26_14.54.04-fml.txt#L38)2] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632) ~[?:1.8.0_382] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_382] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:10[56](https://aternos.org/files/crash-reports/crash-2023-10-26_14.54.04-fml.txt#L56)) ~[?:1.8.0_382] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_382] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) ~[?:1.8.0_382] {}

**Comment by PaintNinja** [comment]
1.16.5 is no longer supported, sorry.
